menu:
  Projects: /projects
  Archives: /archives

catena:
  Design Pattern: '/design-pattern'

duoshuo_short_name: duoshuo_short_name

links:
  about: /about.html
  feed: /atom.xml

# site start time
since: 2014
